.PHONY: clean All

All:
	@echo "----------Building project:[ 1add2cmplx - Debug ]----------"
	@cd "1add2cmplx" && "$(MAKE)" -f  "1add2cmplx.mk"
clean:
	@echo "----------Cleaning project:[ 1add2cmplx - Debug ]----------"
	@cd "1add2cmplx" && "$(MAKE)" -f  "1add2cmplx.mk" clean
