.PHONY: clean All

All:
	@echo "----------Building project:[ 9matrix - Debug ]----------"
	@cd "9matrix" && "$(MAKE)" -f  "9matrix.mk"
clean:
	@echo "----------Cleaning project:[ 9matrix - Debug ]----------"
	@cd "9matrix" && "$(MAKE)" -f  "9matrix.mk" clean
