.PHONY: clean All

All:
	@echo "----------Building project:[ 05 - Debug ]----------"
	@cd "5" && "$(MAKE)" -f  "05.mk"
clean:
	@echo "----------Cleaning project:[ 05 - Debug ]----------"
	@cd "5" && "$(MAKE)" -f  "05.mk" clean
