.PHONY: clean All

All:
	@echo "----------Building project:[ 6feetTOinches - Debug ]----------"
	@cd "6feetTOinches" && "$(MAKE)" -f  "6feetTOinches.mk"
clean:
	@echo "----------Cleaning project:[ 6feetTOinches - Debug ]----------"
	@cd "6feetTOinches" && "$(MAKE)" -f  "6feetTOinches.mk" clean
